<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Z100697" name="Test" tests="13" failures="11" timestamp="23 Aug 2012 06:27:34 GMT" time="225.672" errors="0">
  <testcase name="@AfterClass tearDown" time="0.0" classname="com.registration.tests.Step1">
    <failure type="com.thoughtworks.selenium.SeleniumException" message="ERROR Server Exception: sessionId f14122836b3e493a8ce5f7da038be18d doesn&amp;apos;t exist; perhaps this session was already stopped?">
      <![CDATA[com.thoughtworks.selenium.SeleniumException: ERROR Server Exception: sessionId f14122836b3e493a8ce5f7da038be18d doesn't exist; perhaps this session was already stopped?
	at com.thoughtworks.selenium.HttpCommandProcessor.throwAssertionFailureExceptionOrError(HttpCommandProcessor.java:112)
	at com.thoughtworks.selenium.HttpCommandProcessor.doCommand(HttpCommandProcessor.java:106)
	at com.unitedinternet.portal.selenium.utils.logging.LoggingCommandProcessor.doCommand(LoggingCommandProcessor.java:141)
	at com.thoughtworks.selenium.DefaultSelenium.close(DefaultSelenium.java:427)
	at com.test.fw.SeleniumHelper.dismissSelenium(SeleniumHelper.java:79)
	at com.registration.tests.TestBaseReg.tearDown(TestBaseReg.java:26)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- @AfterClass tearDown -->
  <testcase name="@BeforeClass setUp" time="0.0" classname="com.registration.tests.Step2">
    <skipped/>
  </testcase> <!-- @BeforeClass setUp -->
  <testcase name="@AfterClass tearDown" time="0.0" classname="com.registration.tests.Step2">
    <skipped/>
  </testcase> <!-- @AfterClass tearDown -->
  <testcase name="testStep1" time="1.246" classname="com.registration.tests.Step1">
    <failure type="com.thoughtworks.selenium.SeleniumException" message="ERROR Server Exception: unexpected command json={command:&amp;quot;open&amp;quot;,target:&amp;quot;http://umagicpro-pp/&amp;quot;,value:&amp;quot;&amp;quot;} in place before new command open could be added">
      <![CDATA[com.thoughtworks.selenium.SeleniumException: ERROR Server Exception: unexpected command json={command:"open",target:"http://umagicpro-pp/",value:""} in place before new command open could be added
	at com.thoughtworks.selenium.HttpCommandProcessor.throwAssertionFailureExceptionOrError(HttpCommandProcessor.java:112)
	at com.thoughtworks.selenium.HttpCommandProcessor.doCommand(HttpCommandProcessor.java:106)
	at com.unitedinternet.portal.selenium.utils.logging.LoggingCommandProcessor.doCommand(LoggingCommandProcessor.java:141)
	at com.thoughtworks.selenium.DefaultSelenium.open(DefaultSelenium.java:369)
	at com.registration.tests.Step1.testStep1(Step1.java:11)
	at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testStep1 -->
  <testcase name="testStep1" time="1.309" classname="com.registration.tests.Step1">
    <failure type="com.thoughtworks.selenium.SeleniumException" message="ERROR Server Exception: unexpected command json={command:&amp;quot;open&amp;quot;,target:&amp;quot;http://umagicpro-pp/&amp;quot;,value:&amp;quot;&amp;quot;} in place before new command open could be added">
      <![CDATA[com.thoughtworks.selenium.SeleniumException: ERROR Server Exception: unexpected command json={command:"open",target:"http://umagicpro-pp/",value:""} in place before new command open could be added
	at com.thoughtworks.selenium.HttpCommandProcessor.throwAssertionFailureExceptionOrError(HttpCommandProcessor.java:112)
	at com.thoughtworks.selenium.HttpCommandProcessor.doCommand(HttpCommandProcessor.java:106)
	at com.unitedinternet.portal.selenium.utils.logging.LoggingCommandProcessor.doCommand(LoggingCommandProcessor.java:141)
	at com.thoughtworks.selenium.DefaultSelenium.open(DefaultSelenium.java:369)
	at com.registration.tests.Step1.testStep1(Step1.java:11)
	at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testStep1 -->
  <testcase name="testStep1" time="1.415" classname="com.registration.tests.Step1">
    <failure type="com.thoughtworks.selenium.SeleniumException" message="ERROR Server Exception: unexpected command json={command:&amp;quot;open&amp;quot;,target:&amp;quot;http://umagicpro-pp/&amp;quot;,value:&amp;quot;&amp;quot;} in place before new command open could be added">
      <![CDATA[com.thoughtworks.selenium.SeleniumException: ERROR Server Exception: unexpected command json={command:"open",target:"http://umagicpro-pp/",value:""} in place before new command open could be added
	at com.thoughtworks.selenium.HttpCommandProcessor.throwAssertionFailureExceptionOrError(HttpCommandProcessor.java:112)
	at com.thoughtworks.selenium.HttpCommandProcessor.doCommand(HttpCommandProcessor.java:106)
	at com.unitedinternet.portal.selenium.utils.logging.LoggingCommandProcessor.doCommand(LoggingCommandProcessor.java:141)
	at com.thoughtworks.selenium.DefaultSelenium.open(DefaultSelenium.java:369)
	at com.registration.tests.Step1.testStep1(Step1.java:11)
	at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testStep1 -->
  <testcase name="testStep1" time="1.595" classname="com.registration.tests.Step1">
    <failure type="com.thoughtworks.selenium.SeleniumException" message="ERROR Server Exception: unexpected command json={command:&amp;quot;open&amp;quot;,target:&amp;quot;http://umagicpro-pp/&amp;quot;,value:&amp;quot;&amp;quot;} in place before new command open could be added">
      <![CDATA[com.thoughtworks.selenium.SeleniumException: ERROR Server Exception: unexpected command json={command:"open",target:"http://umagicpro-pp/",value:""} in place before new command open could be added
	at com.thoughtworks.selenium.HttpCommandProcessor.throwAssertionFailureExceptionOrError(HttpCommandProcessor.java:112)
	at com.thoughtworks.selenium.HttpCommandProcessor.doCommand(HttpCommandProcessor.java:106)
	at com.unitedinternet.portal.selenium.utils.logging.LoggingCommandProcessor.doCommand(LoggingCommandProcessor.java:141)
	at com.thoughtworks.selenium.DefaultSelenium.open(DefaultSelenium.java:369)
	at com.registration.tests.Step1.testStep1(Step1.java:11)
	at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testStep1 -->
  <testcase name="testStep1" time="1.603" classname="com.registration.tests.Step1">
    <failure type="com.thoughtworks.selenium.SeleniumException" message="ERROR Server Exception: unexpected command json={command:&amp;quot;open&amp;quot;,target:&amp;quot;http://umagicpro-pp/&amp;quot;,value:&amp;quot;&amp;quot;} in place before new command open could be added">
      <![CDATA[com.thoughtworks.selenium.SeleniumException: ERROR Server Exception: unexpected command json={command:"open",target:"http://umagicpro-pp/",value:""} in place before new command open could be added
	at com.thoughtworks.selenium.HttpCommandProcessor.throwAssertionFailureExceptionOrError(HttpCommandProcessor.java:112)
	at com.thoughtworks.selenium.HttpCommandProcessor.doCommand(HttpCommandProcessor.java:106)
	at com.unitedinternet.portal.selenium.utils.logging.LoggingCommandProcessor.doCommand(LoggingCommandProcessor.java:141)
	at com.thoughtworks.selenium.DefaultSelenium.open(DefaultSelenium.java:369)
	at com.registration.tests.Step1.testStep1(Step1.java:11)
	at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testStep1 -->
  <testcase name="testStep1" time="1.608" classname="com.registration.tests.Step1">
    <failure type="com.thoughtworks.selenium.SeleniumException" message="ERROR Server Exception: unexpected command json={command:&amp;quot;open&amp;quot;,target:&amp;quot;http://umagicpro-pp/&amp;quot;,value:&amp;quot;&amp;quot;} in place before new command open could be added">
      <![CDATA[com.thoughtworks.selenium.SeleniumException: ERROR Server Exception: unexpected command json={command:"open",target:"http://umagicpro-pp/",value:""} in place before new command open could be added
	at com.thoughtworks.selenium.HttpCommandProcessor.throwAssertionFailureExceptionOrError(HttpCommandProcessor.java:112)
	at com.thoughtworks.selenium.HttpCommandProcessor.doCommand(HttpCommandProcessor.java:106)
	at com.unitedinternet.portal.selenium.utils.logging.LoggingCommandProcessor.doCommand(LoggingCommandProcessor.java:141)
	at com.thoughtworks.selenium.DefaultSelenium.open(DefaultSelenium.java:369)
	at com.registration.tests.Step1.testStep1(Step1.java:11)
	at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testStep1 -->
  <testcase name="testStep1" time="219.452" classname="com.registration.tests.Step1">
    <failure type="com.thoughtworks.selenium.SeleniumException" message="Connection refused: connect">
      <![CDATA[com.thoughtworks.selenium.SeleniumException: Connection refused: connect
	at com.thoughtworks.selenium.HttpCommandProcessor.executeCommandOnServlet(HttpCommandProcessor.java:121)
	at com.thoughtworks.selenium.HttpCommandProcessor.doCommand(HttpCommandProcessor.java:101)
	at com.unitedinternet.portal.selenium.utils.logging.LoggingCommandProcessor.doCommand(LoggingCommandProcessor.java:141)
	at com.unitedinternet.portal.selenium.utils.logging.LoggingCommandProcessor.doAutomaticScreenshot(LoggingCommandProcessor.java:494)
	at com.unitedinternet.portal.selenium.utils.logging.LoggingCommandProcessor.doExceptionLogging(LoggingCommandProcessor.java:386)
	at com.unitedinternet.portal.selenium.utils.logging.LoggingCommandProcessor.doCommand(LoggingCommandProcessor.java:143)
	at com.unitedinternet.portal.selenium.utils.logging.LoggingCommandProcessor.doAutomaticScreenshot(LoggingCommandProcessor.java:494)
	at com.unitedinternet.portal.selenium.utils.logging.LoggingCommandProcessor.doExceptionLogging(LoggingCommandProcessor.java:386)
	at com.unitedinternet.portal.selenium.utils.logging.LoggingCommandProcessor.doCommand(LoggingCommandProcessor.java:143)
	at com.unitedinternet.portal.selenium.utils.logging.LoggingCommandProcessor.doAutomaticScreenshot(LoggingCommandProcessor.java:494)
	at com.unitedinternet.portal.selenium.utils.logging.LoggingCommandProcessor.doExceptionLogging(LoggingCommandProcessor.java:386)
	at com.unitedinternet.portal.selenium.utils.logging.LoggingCommandProcessor.doCommand(LoggingCommandProcessor.java:143)
	at com.unitedinternet.portal.selenium.utils.logging.LoggingCommandProcessor.doAutomaticScreenshot(LoggingCommandProcessor.java:494)
	at com.unitedinternet.portal.selenium.utils.logging.LoggingCommandProcessor.doExceptionLogging(LoggingCommandProcessor.java:386)
	at com.unitedinternet.portal.selenium.utils.logging.LoggingCommandProcessor.doCommand(LoggingCommandProcessor.java:143)
	at com.thoughtworks.selenium.DefaultSelenium.open(DefaultSelenium.java:369)
	at com.registration.tests.Step1.testStep1(Step1.java:11)
	at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at sun.net.NetworkClient.doConnect(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.<init>(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(Unknown Source)
	at com.thoughtworks.selenium.HttpCommandProcessor.getOutputStreamWriter(HttpCommandProcessor.java:149)
	at com.thoughtworks.selenium.HttpCommandProcessor.getCommandResponseAsString(HttpCommandProcessor.java:176)
	at com.thoughtworks.selenium.HttpCommandProcessor.executeCommandOnServlet(HttpCommandProcessor.java:118)
	... 33 more
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testStep1 -->
  <testcase name="testStep1" time="219.548" classname="com.registration.tests.Step1">
    <failure type="com.thoughtworks.selenium.SeleniumException" message="Connection refused: connect">
      <![CDATA[com.thoughtworks.selenium.SeleniumException: Connection refused: connect
	at com.thoughtworks.selenium.HttpCommandProcessor.executeCommandOnServlet(HttpCommandProcessor.java:121)
	at com.thoughtworks.selenium.HttpCommandProcessor.doCommand(HttpCommandProcessor.java:101)
	at com.unitedinternet.portal.selenium.utils.logging.LoggingCommandProcessor.doCommand(LoggingCommandProcessor.java:141)
	at com.unitedinternet.portal.selenium.utils.logging.LoggingCommandProcessor.doAutomaticScreenshot(LoggingCommandProcessor.java:494)
	at com.unitedinternet.portal.selenium.utils.logging.LoggingCommandProcessor.doExceptionLogging(LoggingCommandProcessor.java:386)
	at com.unitedinternet.portal.selenium.utils.logging.LoggingCommandProcessor.doCommand(LoggingCommandProcessor.java:143)
	at com.thoughtworks.selenium.DefaultSelenium.open(DefaultSelenium.java:369)
	at com.registration.tests.Step1.testStep1(Step1.java:11)
	at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at sun.net.NetworkClient.doConnect(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.<init>(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(Unknown Source)
	at com.thoughtworks.selenium.HttpCommandProcessor.getOutputStreamWriter(HttpCommandProcessor.java:149)
	at com.thoughtworks.selenium.HttpCommandProcessor.getCommandResponseAsString(HttpCommandProcessor.java:176)
	at com.thoughtworks.selenium.HttpCommandProcessor.executeCommandOnServlet(HttpCommandProcessor.java:118)
	... 24 more
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testStep1 -->
  <testcase name="testStep1Find" time="0.828" classname="com.registration.tests.Step1">
    <failure type="com.thoughtworks.selenium.SeleniumException" message="ERROR Server Exception: sessionId f14122836b3e493a8ce5f7da038be18d doesn&amp;apos;t exist; perhaps this session was already stopped?">
      <![CDATA[com.thoughtworks.selenium.SeleniumException: ERROR Server Exception: sessionId f14122836b3e493a8ce5f7da038be18d doesn't exist; perhaps this session was already stopped?
	at com.thoughtworks.selenium.HttpCommandProcessor.throwAssertionFailureExceptionOrError(HttpCommandProcessor.java:112)
	at com.thoughtworks.selenium.HttpCommandProcessor.doCommand(HttpCommandProcessor.java:106)
	at com.thoughtworks.selenium.HttpCommandProcessor.getString(HttpCommandProcessor.java:275)
	at com.thoughtworks.selenium.HttpCommandProcessor.getBoolean(HttpCommandProcessor.java:348)
	at com.unitedinternet.portal.selenium.utils.logging.LoggingCommandProcessor.getBoolean(LoggingCommandProcessor.java:168)
	at com.thoughtworks.selenium.DefaultSelenium.isAlertPresent(DefaultSelenium.java:431)
	at com.registration.tests.Step1.testStep1Find(Step1.java:36)
	at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testStep1Find -->
  <testcase name="testStep1Find" time="0.966" classname="com.registration.tests.Step1">
    <failure type="com.thoughtworks.selenium.SeleniumException" message="ERROR Server Exception: sessionId f14122836b3e493a8ce5f7da038be18d doesn&amp;apos;t exist; perhaps this session was already stopped?">
      <![CDATA[com.thoughtworks.selenium.SeleniumException: ERROR Server Exception: sessionId f14122836b3e493a8ce5f7da038be18d doesn't exist; perhaps this session was already stopped?
	at com.thoughtworks.selenium.HttpCommandProcessor.throwAssertionFailureExceptionOrError(HttpCommandProcessor.java:112)
	at com.thoughtworks.selenium.HttpCommandProcessor.doCommand(HttpCommandProcessor.java:106)
	at com.thoughtworks.selenium.HttpCommandProcessor.getString(HttpCommandProcessor.java:275)
	at com.thoughtworks.selenium.HttpCommandProcessor.getBoolean(HttpCommandProcessor.java:348)
	at com.unitedinternet.portal.selenium.utils.logging.LoggingCommandProcessor.getBoolean(LoggingCommandProcessor.java:168)
	at com.thoughtworks.selenium.DefaultSelenium.isAlertPresent(DefaultSelenium.java:431)
	at com.registration.tests.Step1.testStep1Find(Step1.java:36)
	at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testStep1Find -->
  <testcase name="testStep1Find" time="0.995" classname="com.registration.tests.Step1">
    <failure type="com.thoughtworks.selenium.SeleniumException" message="ERROR Server Exception: sessionId f14122836b3e493a8ce5f7da038be18d doesn&amp;apos;t exist; perhaps this session was already stopped?">
      <![CDATA[com.thoughtworks.selenium.SeleniumException: ERROR Server Exception: sessionId f14122836b3e493a8ce5f7da038be18d doesn't exist; perhaps this session was already stopped?
	at com.thoughtworks.selenium.HttpCommandProcessor.throwAssertionFailureExceptionOrError(HttpCommandProcessor.java:112)
	at com.thoughtworks.selenium.HttpCommandProcessor.doCommand(HttpCommandProcessor.java:106)
	at com.thoughtworks.selenium.HttpCommandProcessor.getString(HttpCommandProcessor.java:275)
	at com.thoughtworks.selenium.HttpCommandProcessor.getBoolean(HttpCommandProcessor.java:348)
	at com.unitedinternet.portal.selenium.utils.logging.LoggingCommandProcessor.getBoolean(LoggingCommandProcessor.java:168)
	at com.thoughtworks.selenium.DefaultSelenium.isAlertPresent(DefaultSelenium.java:431)
	at com.registration.tests.Step1.testStep1Find(Step1.java:36)
	at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testStep1Find -->
  <testcase name="testStep2" time="0.0" classname="com.registration.tests.Step2">
    <skipped/>
  </testcase> <!-- testStep2 -->
  <testcase name="testStep2" time="0.001" classname="com.registration.tests.Step2">
    <skipped/>
  </testcase> <!-- testStep2 -->
</testsuite> <!-- Test -->
