<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Z100697" name="com.example.tests.Step2Ex" tests="2" failures="2" timestamp="22 Aug 2012 14:14:24 GMT" time="0.000" errors="0">
  <testcase name="testStep2" time="0.000" classname="com.example.tests.Step2Ex">
    <failure type="java.lang.RuntimeException" message="ERROR while creating file: &#039;./log/result.Step2Ex22.08.2012_18/14/240.html&#039;">
      <![CDATA[java.lang.RuntimeException: ERROR while creating file: './log/result.Step2Ex22.08.2012_18/14/240.html'
	at com.unitedinternet.portal.selenium.utils.logging.LoggingUtils.createWriter(LoggingUtils.java:76)
	at com.example.tests.SeleniumHelperEx.createNewLoggingSelenium(SeleniumHelperEx.java:68)
	at com.example.tests.SeleniumHelperEx.getSelenium(SeleniumHelperEx.java:29)
	at com.example.tests.TestBaseEx.setUp(TestBaseEx.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:175)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:107)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: java.io.IOException: Системе не удается найти указанный путь
	at java.io.WinNTFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(Unknown Source)
	at com.unitedinternet.portal.selenium.utils.logging.LoggingUtils.createWriter(LoggingUtils.java:61)
	... 27 more
]]>
    </failure>
  </testcase> <!-- testStep2 -->
  <testcase name="testStep2" time="0.000" classname="com.example.tests.Step2Ex">
    <failure type="java.lang.RuntimeException" message="ERROR while creating file: &#039;./log/result.Step2Ex22.08.2012_18/14/240.html&#039;">
      <![CDATA[java.lang.RuntimeException: ERROR while creating file: './log/result.Step2Ex22.08.2012_18/14/240.html'
	at com.unitedinternet.portal.selenium.utils.logging.LoggingUtils.createWriter(LoggingUtils.java:76)
	at com.example.tests.SeleniumHelperEx.createNewLoggingSelenium(SeleniumHelperEx.java:68)
	at com.example.tests.SeleniumHelperEx.getSelenium(SeleniumHelperEx.java:29)
	at com.example.tests.TestBaseEx.setUp(TestBaseEx.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:175)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:107)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1197)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1122)
	at org.testng.TestNG.run(TestNG.java:1030)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: java.io.IOException: Системе не удается найти указанный путь
	at java.io.WinNTFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(Unknown Source)
	at com.unitedinternet.portal.selenium.utils.logging.LoggingUtils.createWriter(LoggingUtils.java:61)
	... 27 more
]]>
    </failure>
  </testcase> <!-- testStep2 -->
</testsuite> <!-- com.example.tests.Step2Ex -->
